import Link from "next/link";


export default function Body() {
    return(
        <div className="bg-blue-400">
            <div className=" bg-blue-400 md:flex bg-slate-100 p-8 md:p-0 dark:bg-slate-800">
                <Link href="card">
                    <img
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiS2RF6QI1BAp_uZhTXosG_dMYWw5I5SqplLchE0rRyQ2EGvfiKmo8YuQvb7-Angj2wl4&usqp=CAU"
                        alt="" className="cursor-pointer w-auto h-auto md:rounded-none rounded-full mx-auto"/>
                </Link>
                <div className="pt-6 md:p-8 text-center md:text-left space-y-4  bg-blue-400">
                    <blockquote>
                        <p className="text-lg font-light">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dapibus tincidunt euismod. Vivamus a sapien at odio maximus cursus. Aenean a felis lectus. Morbi posuere sem velit, ut ultricies tortor sagittis laoreet. Quisque nec dui vitae dui molestie interdum. Sed mollis ut nisl sed fermentum. Nulla facilisi. Phasellus ultricies viverra turpis, vel ultrices metus egestas egestas. Nam sollicitudin neque efficitur, dignissim dolor vitae, eleifend purus. Vivamus consectetur a justo ut vestibulum. Aenean lorem urna, sagittis luctus nulla at, ullamcorper fringilla nisi. Donec porta dui leo, at sodales ante ornare at. Integer sit amet ornare enim. Integer ornare felis sed magna interdum ornare.
                            Ut et orci facilisis, bibendum mi sit amet, viverra sem. Nunc quis laoreet mauris. Phasellus semper eros ultricies, finibus dui eget, viverra turpis. Maecenas ut facilisis tortor. Nunc interdum erat vitae sapien posuere sollicitudin. Vivamus malesuada cursus tellus a posuere. Maecenas sem sem, maximus ac urna venenatis, euismod mattis sem. Duis maximus, nulla tincidunt fermentum lobortis, eros turpis commodo est, sit amet molestie turpis sem in augue. Vestibulum laoreet, metus non dictum venenatis, felis purus porttitor enim, vel laoreet ligula leo at purus. Nulla facilisi.
                            Pellentesque eu aliquam nunc. Duis sodales neque enim, at ultrices quam egestas sed. Proin egestas ipsum ac molestie interdum. Donec eget ornare mauris. Phasellus interdum urna sed maximus molestie. Morbi sed odio in lacus mattis venenatis. In in eros et neque pharetra porttitor scelerisque non felis. Vestibulum hendrerit nulla eu tempor luctus. Nullam viverra quam id mi aliquam molestie. Sed a interdum massa. Aliquam sed luctus ex, sed molestie dolor. Nam tempor id justo eu ullamcorper. Quisque sagittis nec augue et accumsan. Quisque quam mauris, interdum id nunc vitae, luctus mollis odio. Integer blandit diam quam, vitae sagittis sapien eleifend quis. Maecenas ac mauris eleifend, placerat sapien a, tincidunt risus.
                            Nulla mattis bibendum lobortis. Duis a laoreet sem, vitae ultricies massa. Vestibulum varius nunc non risus sollicitudin pulvinar. Etiam auctor lacus et turpis mollis molestie. Sed feugiat odio ligula, sed efficitur nulla molestie a. Suspendisse potenti. Proin auctor sit amet eros sed aliquet. Cras accumsan, dolor vitae efficitur luctus, ante odio lobortis nisi, eu mollis purus eros in ipsum.
                            Maecenas placerat libero sit amet felis porta pharetra. Quisque hendrerit, nulla eget faucibus fringilla, sapien turpis rhoncus dolor, eu porttitor felis nulla ac nisl. Proin malesuada ornare dui, id consectetur libero vestibulum eu. Proin volutpat at libero in pretium. Aliquam efficitur imperdiet lacus et feugiat. Nunc pulvinar sollicitudin erat, quis semper metus eleifend vitae. Suspendisse potenti. Nullam cursus egestas tortor, eu hendrerit libero maximus ac. Phasellus eu lectus mollis, tincidunt justo at, auctor enim. Sed tortor turpis, porttitor luctus orci id, vehicula feugiat justo. Aenean porta sem ac scelerisque volutpat. Donec vitae ante sagittis, lacinia metus at, sodales purus. Aliquam cursus tortor malesuada nisi posuere, non lobortis leo ultricies. Morbi commodo eget odio eu aliquet.
                            Ut id rhoncus massa. Duis ut diam id mauris egestas tincidunt vitae non mauris. Donec quis dapibus eros, eget dictum nisi. Ut maximus at nunc at maximus. Proin aliquet libero eget lacus consequat ullamcorper. Aliquam bibendum faucibus bibendum. Nulla tincidunt molestie erat efficitur pharetra. Integer viverra orci nibh, in mollis tortor lacinia nec. Integer pulvinar nisi quis sem hendrerit aliquam.
                            Ut sed bibendum urna. Duis hendrerit mi ac arcu finibus imperdiet. Phasellus mattis, turpis ac aliquam viverra, sapien sem porta est, sit amet vestibulum mi augue quis enim. Nam quam ex, malesuada vel ante quis, commodo finibus lectus. Pellentesque vitae tristique massa. Donec condimentum, eros nec dictum pellentesque, elit diam facilisis sem, in mollis metus tortor sed neque. Maecenas dignissim vehicula odio, a pretium justo tempus sed. Sed mattis magna ac mauris pulvinar ullamcorper. Aenean mollis urna non odio ullamcorper ultricies. Aliquam erat volutpat. Donec luctus sed leo et vestibulum.
                            Curabitur a nulla eget est porta auctor. Ut pellentesque et nunc pulvinar facilisis. Donec odio ipsum, tristique sed odio id, ornare blandit nisl. Etiam leo leo, rhoncus nec accumsan eu, faucibus vel nulla. Nullam faucibus ut lorem tristique congue. Sed interdum, ipsum nec vestibulum blandit, nisi nunc aliquet erat, non rhoncus elit dolor in dui. Duis velit eros, bibendum sit amet fringilla id, egestas sed ex. Nullam rhoncus risus quam, eget congue arcu feugiat ut. Quisque mollis, eros vel euismod convallis, justo dui interdum lorem, ac pulvinar sapien purus eleifend ligula. Aenean venenatis enim ut viverra sollicitudin. Donec ut nulla at tortor accumsan interdum. Suspendisse tortor dolor, ultrices ut tellus vel, lobortis malesuada erat. Suspendisse dignissim, leo ut cursus cursus, justo orci ornare risus, nec posuere nisi orci vel dui. Cras nec est et augue dignissim imperdiet.
                            Duis tempor erat vel consequat maximus. Nulla molestie, massa a vulputate blandit, sem ante malesuada nunc, nec ullamcorper diam diam et metus. Vestibulum ut nisi a nisl finibus rutrum non et urna. Duis mollis sapien quis nibh commodo dapibus. Nullam bibendum a nunc ac malesuada. Sed suscipit, nisi a molestie consequat, lacus nunc dictum nisi, sit amet euismod felis felis vitae tortor. Nullam dignissim euismod congue. Vestibulum lorem sapien, tincidunt vel laoreet ut, luctus nec augue.
                            Mauris imperdiet ullamcorper velit, vel rutrum ex placerat eget. Donec vitae lorem accumsan, imperdiet felis semper, vehicula elit. Integer ante lorem, venenatis id ex sed, auctor eleifend risus. Pellentesque sit amet bibendum mauris. Donec volutpat suscipit turpis eu iaculis. Pellentesque mattis non felis nec volutpat. Nullam gravida et velit non bibendum. Proin bibendum erat nunc, eget sodales mauris porttitor vitae. Etiam eget felis at leo semper viverra. Cras cursus vehicula mauris, et scelerisque nibh consectetur nec. Sed feugiat quam eget velit ultrices consequat. Praesent et ipsum ligula. Sed ac finibus orci. Cras enim risus, cursus et porta ut, venenatis nec purus. Sed purus diam, convallis nec enim eget, consequat rutrum lacus.
                            </p>
                    </blockquote>
                </div>
            </div>
        </div>
    )
}
